#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class EventType(object):
    Stop = 1
    GeoFenceEntry = 2
    GeoFenceLeave = 3
    GeoFenceSpeedingBegin = 4
    GeoFenceSpeedingEnd = 5
    SpeedingBegin = 6
    SpeedingEnd = 7
    Start = 8
    DeviceAlarm = 11
    TripScheduled = 14
    TripStart = 15
    TripEnd = 16
    TripAborted = 17
    TripDeleted = 18
    TripOverlap = 19
    RouteDeviation = 20
    RouteReturn = 21
    TripPointEntry = 22
    TripPointLeave = 23
    TripPointSkip = 24
    ScheduleReturn = 27
    TripPointOutOfTurn = 28
    SensorBegin = 29
    SensorEnd = 30
    InactivityBegin = 31
    InactivityEnd = 32
    DelayedInGeofence = 33
    FuelAdditionBegin = 35
    FuelAdditionEnd = 36
    FuelRemovalBegin = 37
    FuelRemovalEnd = 38
    DeviceConnected = 39
    DeviceDisconnected = 40
    TooCloseBegin = 41
    TooCloseEnd = 42
    TooFarBegin = 43
    TooFarEnd = 44
    SpeedingOnRoadBegin = 45
    SpeedingOnRoadEnd = 46
    HarshAccelerationBegin = 47
    HarshAccelerationEnd = 48
    HarshBrakingBegin = 49
    HarshBrakingEnd = 50
    HarshTurnBegin = 51
    HarshTurnEnd = 52
    SpeedingPenaltyBegin = 53
    SpeedingPenaltyEnd = 54
    RoughRoadBegin = 55
    RoughRoadEnd = 56
    GeoFenceSensorBegin = 57
    GeoFenceSensorEnd = 58
    AlarmBegin = 59
    AlarmEnd = 60
    MaintenanceDone = 61
    MaintenanceOverdue = 62
    FuelOverConsumptionBegin = 63
    FuelOverConsumptionEnd = 64
    MaintenanceSoon = 65
    AbsenceFromTrip = 66
    SoonTripEnd = 67
    DisconnectedOnTripBegin = 68
    DisconnectedOnTripEnd = 69
    UnscheduledStopOnTripBegin = 70
    UnscheduledStopOnTripEnd = 71
    AlarmOnTripBegin = 72
    AlarmOnTripEnd = 73
    EarlyArrivalOnTrip = 74
    LateArrivalOnTrip = 75
    EarlyDepartureOnTrip = 76
    LateDepartureOnTrip = 77
    SwitchingToAlternativeRoute = 78
    TripCanceled = 79
    TripPointShift = 80
    TripVehicleAssignment = 81
    TripVehicleWithdrawal = 82
    TrackerBroken = 83
    NoMovementBegin = 85
    NoMovementEnd = 86
    RoadAccident = 87
    PhotoEvent = 10000

    _VALUES_TO_NAMES = {
        1: "Stop",
        2: "GeoFenceEntry",
        3: "GeoFenceLeave",
        4: "GeoFenceSpeedingBegin",
        5: "GeoFenceSpeedingEnd",
        6: "SpeedingBegin",
        7: "SpeedingEnd",
        8: "Start",
        11: "DeviceAlarm",
        14: "TripScheduled",
        15: "TripStart",
        16: "TripEnd",
        17: "TripAborted",
        18: "TripDeleted",
        19: "TripOverlap",
        20: "RouteDeviation",
        21: "RouteReturn",
        22: "TripPointEntry",
        23: "TripPointLeave",
        24: "TripPointSkip",
        27: "ScheduleReturn",
        28: "TripPointOutOfTurn",
        29: "SensorBegin",
        30: "SensorEnd",
        31: "InactivityBegin",
        32: "InactivityEnd",
        33: "DelayedInGeofence",
        35: "FuelAdditionBegin",
        36: "FuelAdditionEnd",
        37: "FuelRemovalBegin",
        38: "FuelRemovalEnd",
        39: "DeviceConnected",
        40: "DeviceDisconnected",
        41: "TooCloseBegin",
        42: "TooCloseEnd",
        43: "TooFarBegin",
        44: "TooFarEnd",
        45: "SpeedingOnRoadBegin",
        46: "SpeedingOnRoadEnd",
        47: "HarshAccelerationBegin",
        48: "HarshAccelerationEnd",
        49: "HarshBrakingBegin",
        50: "HarshBrakingEnd",
        51: "HarshTurnBegin",
        52: "HarshTurnEnd",
        53: "SpeedingPenaltyBegin",
        54: "SpeedingPenaltyEnd",
        55: "RoughRoadBegin",
        56: "RoughRoadEnd",
        57: "GeoFenceSensorBegin",
        58: "GeoFenceSensorEnd",
        59: "AlarmBegin",
        60: "AlarmEnd",
        61: "MaintenanceDone",
        62: "MaintenanceOverdue",
        63: "FuelOverConsumptionBegin",
        64: "FuelOverConsumptionEnd",
        65: "MaintenanceSoon",
        66: "AbsenceFromTrip",
        67: "SoonTripEnd",
        68: "DisconnectedOnTripBegin",
        69: "DisconnectedOnTripEnd",
        70: "UnscheduledStopOnTripBegin",
        71: "UnscheduledStopOnTripEnd",
        72: "AlarmOnTripBegin",
        73: "AlarmOnTripEnd",
        74: "EarlyArrivalOnTrip",
        75: "LateArrivalOnTrip",
        76: "EarlyDepartureOnTrip",
        77: "LateDepartureOnTrip",
        78: "SwitchingToAlternativeRoute",
        79: "TripCanceled",
        80: "TripPointShift",
        81: "TripVehicleAssignment",
        82: "TripVehicleWithdrawal",
        83: "TrackerBroken",
        85: "NoMovementBegin",
        86: "NoMovementEnd",
        87: "RoadAccident",
        10000: "PhotoEvent",
    }

    _NAMES_TO_VALUES = {
        "Stop": 1,
        "GeoFenceEntry": 2,
        "GeoFenceLeave": 3,
        "GeoFenceSpeedingBegin": 4,
        "GeoFenceSpeedingEnd": 5,
        "SpeedingBegin": 6,
        "SpeedingEnd": 7,
        "Start": 8,
        "DeviceAlarm": 11,
        "TripScheduled": 14,
        "TripStart": 15,
        "TripEnd": 16,
        "TripAborted": 17,
        "TripDeleted": 18,
        "TripOverlap": 19,
        "RouteDeviation": 20,
        "RouteReturn": 21,
        "TripPointEntry": 22,
        "TripPointLeave": 23,
        "TripPointSkip": 24,
        "ScheduleReturn": 27,
        "TripPointOutOfTurn": 28,
        "SensorBegin": 29,
        "SensorEnd": 30,
        "InactivityBegin": 31,
        "InactivityEnd": 32,
        "DelayedInGeofence": 33,
        "FuelAdditionBegin": 35,
        "FuelAdditionEnd": 36,
        "FuelRemovalBegin": 37,
        "FuelRemovalEnd": 38,
        "DeviceConnected": 39,
        "DeviceDisconnected": 40,
        "TooCloseBegin": 41,
        "TooCloseEnd": 42,
        "TooFarBegin": 43,
        "TooFarEnd": 44,
        "SpeedingOnRoadBegin": 45,
        "SpeedingOnRoadEnd": 46,
        "HarshAccelerationBegin": 47,
        "HarshAccelerationEnd": 48,
        "HarshBrakingBegin": 49,
        "HarshBrakingEnd": 50,
        "HarshTurnBegin": 51,
        "HarshTurnEnd": 52,
        "SpeedingPenaltyBegin": 53,
        "SpeedingPenaltyEnd": 54,
        "RoughRoadBegin": 55,
        "RoughRoadEnd": 56,
        "GeoFenceSensorBegin": 57,
        "GeoFenceSensorEnd": 58,
        "AlarmBegin": 59,
        "AlarmEnd": 60,
        "MaintenanceDone": 61,
        "MaintenanceOverdue": 62,
        "FuelOverConsumptionBegin": 63,
        "FuelOverConsumptionEnd": 64,
        "MaintenanceSoon": 65,
        "AbsenceFromTrip": 66,
        "SoonTripEnd": 67,
        "DisconnectedOnTripBegin": 68,
        "DisconnectedOnTripEnd": 69,
        "UnscheduledStopOnTripBegin": 70,
        "UnscheduledStopOnTripEnd": 71,
        "AlarmOnTripBegin": 72,
        "AlarmOnTripEnd": 73,
        "EarlyArrivalOnTrip": 74,
        "LateArrivalOnTrip": 75,
        "EarlyDepartureOnTrip": 76,
        "LateDepartureOnTrip": 77,
        "SwitchingToAlternativeRoute": 78,
        "TripCanceled": 79,
        "TripPointShift": 80,
        "TripVehicleAssignment": 81,
        "TripVehicleWithdrawal": 82,
        "TrackerBroken": 83,
        "NoMovementBegin": 85,
        "NoMovementEnd": 86,
        "RoadAccident": 87,
        "PhotoEvent": 10000,
    }
fix_spec(all_structs)
del all_structs
