from dotenv import dotenv_values

val = dotenv_values(".env")

GLONASS_LOGIN = str(val["GLONASS_LOGIN"])
GLONASS_PASSWORD = str(val["GLONASS_PASSWORD"])
GLONASS_BASED_ADRESS = str(val["GLONASS_BASED_ADRESS"])

SCOUT_TREEHUNDRED_LOGIN = str(val["SCOUT_TREEHUNDRED_LOGIN"])
SCOUT_TREEHUNDRED_PASSWORD = str(val["SCOUT_TREEHUNDRED_PASSWORD"])
SCOUT_TREEHUNDRED_BASED_ADRESS = str(val["SCOUT_TREEHUNDRED_BASED_ADRESS"])
SCOUT_TREEHUNDRED_BASE_TOKEN = str(val["SCOUT_TREEHUNDRED_BASE_TOKEN"])
