version: '3.9'
networks:
  migration_network:
    driver: bridge

services:
  web:
    build:
      context: .
      
    environment:
      DEBUG: ${DEBUG}

      ENV GLONASS_LOGIN: ${GLONASS_LOGIN}
      ENV GLONASS_PASSWORD: ${GLONASS_PASSWORD}
      ENV GLONASS_BASED_ADRESS: ${GLONASS_BASED_ADRESS}
      ENV SCOUT_TREEHUNDRED_LOGIN: ${SCOUT_TREEHUNDRED_LOGIN}
      ENV SCOUT_TREEHUNDRED_PASSWORD: ${SCOUT_TREEHUNDRED_PASSWORD}
      ENV SCOUT_TREEHUNDRED_BASED_ADRESS: ${SCOUT_TREEHUNDRED_BASED_ADRESS}
      ENV SCOUT_TREEHUNDRED_BASE_TOKEN: ${SCOUT_TREEHUNDRED_BASE_TOKEN}
      ENV GELIOS_BASED_ADRES: ${GELIOS_BASED_ADRESS}
      ENV GELIOS_LOGIN: ${GELIOS_LOGIN}
      ENV GELIOS_PASSWORD: ${GELIOS_PASSWORD}
      ENV FORT_LOGIN: ${FORT_LOGIN}
      ENV FORT_PASSWORD: ${FORT_PASSWORD}
      ENV FORT_BASED_ADRESS: ${FORT_BASED_ADRESS}
      ENV ERA_LOGIN: ${ERA_LOGIN}
      ENV ERA_PASSWORD: ${ERA_PASSWORD}
      ENV ERA_BASED_ADRESS: ${ERA_BASED_ADRESS}
      ENV ERA_PORT: ${ERA_PORT}
      ENV SCOUT_LOCAL_LOGIN: ${SCOUT_LOCAL_LOGIN}
      ENV SCOUT_LOCAL_PASSWORD: ${SCOUT_LOCAL_PASSWORD}
      ENV SCOUT_LOCAL_BASED_ADRESS: ${SCOUT_LOCAL_BASED_ADRESS}
      ENV SCOUT_LOCAL_PORT: ${SCOUT_LOCAL_PORT}
      ENV WIALON_LOCAL_TOKEN: ${WIALON_LOCAL_TOKEN}
      ENV WIALON_LOCAL_BASED_ADRESS: ${WIALON_LOCAL_BASED_ADRESS}
      ENV WIALON_LOCAL_PORT: ${WIALON_LOCAL_PORT}
      ENV WIALON_HOSTING_TOKEN: ${WIALON_HOSTING_TOKEN}
      ENV WIALON_HOSTING_BASED_ADRESS: ${WIALON_HOSTING_BASED_ADRESS}
      ENV WIALON_HOSTING_PORT: ${WIALON_HOSTING_PORT}
      ENV MTS_API_SMS_LOGIN: ${MTS_API_SMS_LOGIN}
      ENV MTS_API_SMS_PASSWORD: ${MTS_API_SMS_PASSWORD}
      ENV MTS_API_SMS_NAMING: ${MTS_API_SMS_NAMING}
      ENV MTS_API_SMS_TEST_TEL: ${MTS_API_SMS_TEST_TEL}

      ENV DB_HOST: ${DB_HOST}
      ENV MYSQL_USER: ${MYSQL_USER}
      ENV MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      ENV MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ENV MYSQL_PORT: ${MYSQL_PORT}
      ENV API_TOKEN: ${API_TOKEN}
    command: uvicorn api_fast_get_json:app --reload
    expose:
      - 8000
    networks:
      - migration_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - migration_network
