version: '3.3'
networks:
  migration_network:
    driver: bridge

services:
  web:
    build:
      context: .
      
    environment:
      GLONASS_LOGIN: ${GLONASS_LOGIN}
      GLONASS_PASSWORD: ${GLONASS_PASSWORD}
      GLONASS_BASED_ADRESS: ${GLONASS_BASED_ADRESS}
      SCOUT_TREEHUNDRED_LOGIN: ${SCOUT_TREEHUNDRED_LOGIN}
      SCOUT_TREEHUNDRED_PASSWORD: ${SCOUT_TREEHUNDRED_PASSWORD}
      SCOUT_TREEHUNDRED_BASED_ADRESS: ${SCOUT_TREEHUNDRED_BASED_ADRESS}
      SCOUT_TREEHUNDRED_BASE_TOKEN: ${SCOUT_TREEHUNDRED_BASE_TOKEN}
      GELIOS_BASED_ADRES: ${GELIOS_BASED_ADRESS}
      GELIOS_LOGIN: ${GELIOS_LOGIN}
      GELIOS_PASSWORD: ${GELIOS_PASSWORD}
      FORT_LOGIN: ${FORT_LOGIN}
      FORT_PASSWORD: ${FORT_PASSWORD}
      FORT_BASED_ADRESS: ${FORT_BASED_ADRESS}
      ERA_LOGIN: ${ERA_LOGIN}
      ERA_PASSWORD: ${ERA_PASSWORD}
      ERA_BASED_ADRESS: ${ERA_BASED_ADRESS}
      ERA_PORT: ${ERA_PORT}
      SCOUT_LOCAL_LOGIN: ${SCOUT_LOCAL_LOGIN}
      SCOUT_LOCAL_PASSWORD: ${SCOUT_LOCAL_PASSWORD}
      SCOUT_LOCAL_BASED_ADRESS: ${SCOUT_LOCAL_BASED_ADRESS}
      SCOUT_LOCAL_PORT: ${SCOUT_LOCAL_PORT}
      WIALON_LOCAL_TOKEN: ${WIALON_LOCAL_TOKEN}
      WIALON_LOCAL_BASED_ADRESS: ${WIALON_LOCAL_BASED_ADRESS}
      WIALON_LOCAL_PORT: ${WIALON_LOCAL_PORT}
      WIALON_HOSTING_TOKEN: ${WIALON_HOSTING_TOKEN}
      WIALON_HOSTING_BASED_ADRESS: ${WIALON_HOSTING_BASED_ADRESS}
      WIALON_HOSTING_PORT: ${WIALON_HOSTING_PORT}
      MTS_API_SMS_LOGIN: ${MTS_API_SMS_LOGIN}
      MTS_API_SMS_PASSWORD: ${MTS_API_SMS_PASSWORD}
      MTS_API_SMS_NAMING: ${MTS_API_SMS_NAMING}
      MTS_API_SMS_TEST_TEL: ${MTS_API_SMS_TEST_TEL}

      DB_HOST: ${DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      API_TOKEN: ${API_TOKEN}
    command: uvicorn api_fast_get_json:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - migration_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 88:88
    networks:
      - migration_network
