#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class SensorType(object):
    PrimaryIgnition = 2
    Speed = 5
    GpsFix = 10
    ExternalPower = 17
    ExternalPowerMv = 18
    AccelerationX = 21
    AccelerationY = 22
    AccelerationZ = 23
    AlarmButton = 24
    TiltAlarm = 33
    CrashAlarm = 34
    CoolantTemperature = 35
    EngineRpm = 36
    FuelPercent = 37
    Mileage = 38
    TotalFuelConsumed = 39
    EngineHours = 41
    InputChunkSize = 48
    InputPackageSize = 49
    OutputChunkSize = 50
    OutputPackageSize = 51
    PrimaryFuelFlowSupplyL = 52
    PrimaryFuelFlowReturnL = 53
    PrimaryFuelTank = 62
    LLSFuelLevelL = 64
    LLSFuelLevelPercent = 65
    LLSFuelLevelRelative = 66
    LLSFuelTemperatureC = 67
    LLSFuelFrequencyHz = 68
    LLSFuelDensityKgm3 = 69
    LLSFuelWeightKg = 70
    AnalogInput = 71
    OneWireInput = 72
    DigitalInput = 73
    SensorInput = 74
    CanInput = 75
    VolgateMv = 76
    PulseCounter = 77
    FrequencyHz = 78
    LoadAxle = 79
    CustomTemperaturesC = 94
    DoorsOpened = 96
    LockState = 97
    SecondaryFuelTank = 98
    SecondaryIgnition = 99
    SecondaryFuelFlowSupplyL = 100
    SecondaryFuelFlowReturnL = 101
    BatteryChargePercents = 115
    CoordinatesSource = 119
    PassengersCounter = 142
    MaxPositiveAccelerationX = 147
    MaxNegativeAccelerationX = 148
    MaxPositiveAccelerationY = 149
    MaxNegativeAccelerationY = 150
    MaxPositiveAccelerationZ = 151
    MaxNegativeAccelerationZ = 152
    InsideTemperatureC = 153
    HoodOpened = 154
    TrunkOpened = 155
    BrakePedalPushed = 156
    ParkingBrakeActivated = 157
    FuelingL = 158
    FuelingDurationSeconds = 159
    FuelUsedDeltaL = 160
    IsMotion = 161
    RoadAccidentAlarm = 162

    _VALUES_TO_NAMES = {
        2: "PrimaryIgnition",
        5: "Speed",
        10: "GpsFix",
        17: "ExternalPower",
        18: "ExternalPowerMv",
        21: "AccelerationX",
        22: "AccelerationY",
        23: "AccelerationZ",
        24: "AlarmButton",
        33: "TiltAlarm",
        34: "CrashAlarm",
        35: "CoolantTemperature",
        36: "EngineRpm",
        37: "FuelPercent",
        38: "Mileage",
        39: "TotalFuelConsumed",
        41: "EngineHours",
        48: "InputChunkSize",
        49: "InputPackageSize",
        50: "OutputChunkSize",
        51: "OutputPackageSize",
        52: "PrimaryFuelFlowSupplyL",
        53: "PrimaryFuelFlowReturnL",
        62: "PrimaryFuelTank",
        64: "LLSFuelLevelL",
        65: "LLSFuelLevelPercent",
        66: "LLSFuelLevelRelative",
        67: "LLSFuelTemperatureC",
        68: "LLSFuelFrequencyHz",
        69: "LLSFuelDensityKgm3",
        70: "LLSFuelWeightKg",
        71: "AnalogInput",
        72: "OneWireInput",
        73: "DigitalInput",
        74: "SensorInput",
        75: "CanInput",
        76: "VolgateMv",
        77: "PulseCounter",
        78: "FrequencyHz",
        79: "LoadAxle",
        94: "CustomTemperaturesC",
        96: "DoorsOpened",
        97: "LockState",
        98: "SecondaryFuelTank",
        99: "SecondaryIgnition",
        100: "SecondaryFuelFlowSupplyL",
        101: "SecondaryFuelFlowReturnL",
        115: "BatteryChargePercents",
        119: "CoordinatesSource",
        142: "PassengersCounter",
        147: "MaxPositiveAccelerationX",
        148: "MaxNegativeAccelerationX",
        149: "MaxPositiveAccelerationY",
        150: "MaxNegativeAccelerationY",
        151: "MaxPositiveAccelerationZ",
        152: "MaxNegativeAccelerationZ",
        153: "InsideTemperatureC",
        154: "HoodOpened",
        155: "TrunkOpened",
        156: "BrakePedalPushed",
        157: "ParkingBrakeActivated",
        158: "FuelingL",
        159: "FuelingDurationSeconds",
        160: "FuelUsedDeltaL",
        161: "IsMotion",
        162: "RoadAccidentAlarm",
    }

    _NAMES_TO_VALUES = {
        "PrimaryIgnition": 2,
        "Speed": 5,
        "GpsFix": 10,
        "ExternalPower": 17,
        "ExternalPowerMv": 18,
        "AccelerationX": 21,
        "AccelerationY": 22,
        "AccelerationZ": 23,
        "AlarmButton": 24,
        "TiltAlarm": 33,
        "CrashAlarm": 34,
        "CoolantTemperature": 35,
        "EngineRpm": 36,
        "FuelPercent": 37,
        "Mileage": 38,
        "TotalFuelConsumed": 39,
        "EngineHours": 41,
        "InputChunkSize": 48,
        "InputPackageSize": 49,
        "OutputChunkSize": 50,
        "OutputPackageSize": 51,
        "PrimaryFuelFlowSupplyL": 52,
        "PrimaryFuelFlowReturnL": 53,
        "PrimaryFuelTank": 62,
        "LLSFuelLevelL": 64,
        "LLSFuelLevelPercent": 65,
        "LLSFuelLevelRelative": 66,
        "LLSFuelTemperatureC": 67,
        "LLSFuelFrequencyHz": 68,
        "LLSFuelDensityKgm3": 69,
        "LLSFuelWeightKg": 70,
        "AnalogInput": 71,
        "OneWireInput": 72,
        "DigitalInput": 73,
        "SensorInput": 74,
        "CanInput": 75,
        "VolgateMv": 76,
        "PulseCounter": 77,
        "FrequencyHz": 78,
        "LoadAxle": 79,
        "CustomTemperaturesC": 94,
        "DoorsOpened": 96,
        "LockState": 97,
        "SecondaryFuelTank": 98,
        "SecondaryIgnition": 99,
        "SecondaryFuelFlowSupplyL": 100,
        "SecondaryFuelFlowReturnL": 101,
        "BatteryChargePercents": 115,
        "CoordinatesSource": 119,
        "PassengersCounter": 142,
        "MaxPositiveAccelerationX": 147,
        "MaxNegativeAccelerationX": 148,
        "MaxPositiveAccelerationY": 149,
        "MaxNegativeAccelerationY": 150,
        "MaxPositiveAccelerationZ": 151,
        "MaxNegativeAccelerationZ": 152,
        "InsideTemperatureC": 153,
        "HoodOpened": 154,
        "TrunkOpened": 155,
        "BrakePedalPushed": 156,
        "ParkingBrakeActivated": 157,
        "FuelingL": 158,
        "FuelingDurationSeconds": 159,
        "FuelUsedDeltaL": 160,
        "IsMotion": 161,
        "RoadAccidentAlarm": 162,
    }
fix_spec(all_structs)
del all_structs
